name: Build Project
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Data
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Aggregate Blocks
        shell: bash
        run: |
          set -x

          npm install # install packages

          NODE_OUTPUT=`node .github/scripts/agg-blocks.mjs 2>&1`

          if [[ ! $NODE_OUTPUT ]];then
            exit 0
          fi

          NODE_OUTPUT="<pre>${NODE_OUTPUT//$'\n'/<br />}</pre>"
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')

          if [[ ! $PR_NUMBER ]]; then
            exit 0
          fi

          jq -n --arg body "$(echo $NODE_OUTPUT)" '{ body: $body }' |\
          curl -sL  -X POST -d @- \
          -H "Content-Type: application/json" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/commits/$GITHUB_SHA/comments"

      - name: Commit files
        run: |
          NEWART=`git diff HEAD@{1} --stat -- ./src/blocks.js | wc -l`
          if [[ $NEWART -le 0 ]];then
            echo "no changes to src/blocks.js"
            exit 0
          fi
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Updated blocks.js card JSON" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Publish
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: src
          CLEAN: true
